mutation AddCard ($title: String!, $description: String, $source: String, $keywords: String, $dateCreated: String) {
  createCard (
    title: $title,
    description: $description,
    source: $source,
    dateCreated: $dateCreated,
    keywords: {
           set: $keywords
           }
 
  ) {
      id
  }
}