
mutation createOneCard ($title: String!, $description: String, $source: String, $keywords: String, $dateCreated: String){
  createOneCard(
    data: {
      title: $title
      description: $description
      source: $source
      dateCreated: $dateCreated
      keywords: $keywords
    }
  ) {
    id
    title
    description
    source
    dateCreated
  }
}
