mutation updateOneCard($title: String! $description: String! $source: String! $dateCreated: String! $id: String){
  updateOneCard(data:{
    title: $title
    description: $description
    source: $source
    dateCreated: $dateCreated
  }, where:{
    id: $id
  }) {
    id,
    title,
    description,
    source,
    keywords,
    dateCreated
  }
}
