mutation updateOneCard ($id: String!, $title: String!, $description: String, $source: String, $keywords: String, $dateCreated: String){
    updateOneCard (where:
    { id: $id},
    data:{
        title: $title,
        description: $description,
        source: $source,
        dateCreated: $dateCreated
        keywords: {
           set: $keywords
           }
        }
    ){
        id
    }
}